root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/nexus"
  cmd = "go build -o ./tmp/nexus ."
  delay = 1000
  exclude_dir = ["tmp", "web", "node_modules"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "sql"]
  kill_delay = "0s"

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
  show_banner = false
