http:
  routers:
    api:
      rule: "PathPrefix(`/api`)"
      service: backend
      entryPoints:
        - web
    web:
      rule: "PathPrefix(`/`)"
      service: web
      entryPoints:
        - web
      priority: 1

  services:
    backend:
      loadBalancer:
        servers:
          - url: "http://backend:8080"
    web:
      loadBalancer:
        servers:
          - url: "http://web:5173"
